name: Upload Deployment URL

on:
  push:
    branches:
      # Uncomment below before merging
      # - master
      # - staging
      # - develop
      # All branches just for testing (remove before merging)
      - '**'
  pull_request:
    branches:
      # Uncomment below before merging
      # - master
      # - staging
      # - develop
      # All branches just for testing (remove before merging)
      - '**'
  deployment_status:

jobs:
  capture-deployment-url:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Capture Deployment URL
        run: |
          echo "DEPLOYMENT_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
      - name: Save Deployment URL
        uses: actions/upload-artifact@v4
        with:
          name: deployment-url
          path: $GITHUB_ENV